#!/bin/sh
. "$(dirname -- "$0")/lib/fixture.sh"
scenario_full_feature_json_pipeline() { t_ready || return; t_pipeline || return; [ "$(cj_length "$(t_state)" /waves)" = 8 ] && [ "$(sqlite3 "$CSTK_KNOWLEDGE_DB" 'SELECT count(*) FROM waves;')" = 8 ]; }
scenario_full_feature_sqlite_pipeline() { t_ready feature sqlite || return; t_pipeline || return; [ "$(cj_length "$(t_state)" /decisions)" = 8 ]; }
scenario_pause_closes_without_advancing_and_resumes_phase() { t_ready || return; t_good open_wave || return; t_pause || return; t_expect /current_stage specify || return; t_good open_wave || return; [ "$CX_WAVE" = onda-002 ]; }
scenario_missing_evidence_and_unknown_sources_never_advance() { t_ready || return; t_good open_wave || return; t_bad complete '{"evidence_paths":["missing.md"],"rationale":"Checked actual missing evidence and cannot advance."}' || return; t_evidence spec.md; t_bad complete '{"evidence_paths":["docs/specs/test-feature/spec.md"],"rationale":"Actual evidence read and analyzed before phase completion.","used_sources":["invented-source"]}' || return; t_expect /current_stage specify; }
scenario_manual_metering_budget_prevents_advance() { t_ready || return; t_good open_wave || return; t_field .budgets.tool_calls_threshold_wave 1 || return; sh "$T_RUNTIME/state-ondas.sh" tool-call-tick --state-dir "$CX_STATE" >/dev/null; t_evidence spec.md; t_bad complete '{"evidence_paths":["docs/specs/test-feature/spec.md"],"rationale":"Actual artifacts checked but budget must permit advancement."}'; }
scenario_human_block_closes_wave_and_preserves_stage() { t_ready || return; t_good open_wave || return; t_good block '{"context":"Actual operator decision required for source.","question":"Which source should be used for the implementation?","rationale":"Missing actual source prevents evidenced implementation."}' || return; t_bad open_wave || return; t_expect /current_stage specify; }
scenario_recovery_is_explicit_and_idempotent() { t_ready || return; sh "$T_RUNTIME/state-ondas.sh" start --state-dir "$CX_STATE" >/dev/null || return; t_bad open_wave || return; t_good recover || return; t_good recover || return; [ "$(cj_get "$CX_RESULT" /recovered)" = false ]; }
scenario_completion_report_failure_still_releases_lock() { t_ready || return; t_good open_wave || return; t_evidence spec.md; ln -s "$TMPDIR_TEST/external" "$CX_STATE/feature-00c-report.md"; t_bad complete '{"evidence_paths":["docs/specs/test-feature/spec.md"],"rationale":"Actual artifacts checked before phase completion."}' || return; [ ! -d "$CX_STATE/.lock" ] && [ -z "$CX_WAVE" ]; }
run_all_scenarios
