#!/bin/sh
. "$(dirname -- "$0")/lib/fixture.sh"
t_block() { t_good open_wave && t_good block '{"context":"Source for implementation needs actual operator input.","question":"Which validated source should the phase use?","rationale":"Actual operator response is necessary to continue safely."}'; }
scenario_resume_answers_one_block_and_preserves_stage() { t_ready || return; t_block || return; t_good resume '{"answer":"Use the approved local source only.","response_source":"Actual operator fixture response"}' || return; t_expect /human_blocks/0/status respondido || return; [ "$CX_STAGE" = specify ]; }
scenario_answer_is_immutable_and_idempotent() { t_ready || return; t_block || return; CX_RESUME_OPEN=false; t_good resume '{"block_id":"block-001","answer":"Use the approved local source only.","response_source":"Actual operator fixture response"}' || return; _lc_before=$(t_state); t_good resume '{"block_id":"block-001","answer":"Use the approved local source only.","response_source":"Actual operator fixture response"}' || return; cj_equal "$_lc_before" "$(t_state)" || return; t_bad resume '{"block_id":"block-001","answer":"Replace the previously recorded operator answer.","response_source":"Actual operator fixture response"}'; }
scenario_no_fabricated_or_broadcast_answer() { t_ready || return; t_block || return; t_bad resume '{"response_source":"Actual operator fixture response"}' || return; t_bad resume '{"block_id":"unknown-block","answer":"Use local reviewed source.","response_source":"Actual operator fixture response"}'; }
scenario_abort_open_wave_preserves_artifacts_and_is_terminal() { t_ready || return; t_evidence spec.md; t_good open_wave || return; t_good abort '{"reason":"Operator stopped this execution explicitly."}' || return; t_expect /execution/status abortada || return; t_good abort || return; [ -f "$T_FEATURE/spec.md" ] && [ ! -d "$CX_STATE/.lock" ] && [ "$(cj_length "$(t_state)" /waves)" = 1 ]; }
scenario_abort_survives_deleted_governance() { t_ready || return; rm "$T_PROJECT/docs/constitution.md"; t_good status || return; t_good abort || return; t_expect /execution/status abortada; }
scenario_abort_backup_symlink_is_not_followed() { t_ready || return; mkdir "$TMPDIR_TEST/outside"; ln -s "$TMPDIR_TEST/outside" "$CX_STATE/backups"; t_bad abort || return; t_expect /execution/status em_andamento; }
scenario_purge_is_explicit_and_scoped() { t_ready || return; t_good open_wave || return; t_pause || return; t_good abort '{"purge_backups":true}' || return; [ ! -d "$CX_STATE/backups" ] && [ -f "$CX_STATE/state.json" ]; }
scenario_handoff_records_origin_and_preserves_identity() { t_ready || return; t_field .execution_provenance.runtime '"claude-code"' || return; _lc_id=$(cj_get "$(t_state)" /execution/id); t_bad resume || return; t_good handoff '{"expected_runtime":"claude-code","response_source":"Actual operator fixture response","rationale":"Explicit reviewed transfer preserving all existing execution history."}' || return; t_expect /execution_provenance/runtime codex && t_expect /execution/id "$_lc_id"; }
scenario_governance_reconcile_requires_both_reviewed_hashes() { t_ready || return; printf 'Reviewed new rule\n' >> "$T_PROJECT/docs/constitution.md"; t_bad resume || return; t_bad reconcile_governance '{"expected_hashes":["wrong"],"response_source":"Actual operator fixture response","rationale":"Explicitly reviewed governance changes before reconciliation."}' || return; _lc_hashes=$(printf '[%s,%s]' "$(cj_quote "briefing:$(cx_sha "$T_PROJECT/docs/briefing.md")")" "$(cj_quote "constitution:$(cx_sha "$T_PROJECT/docs/constitution.md")")"); t_good reconcile_governance "$(printf '{"expected_hashes":%s,"response_source":"Actual operator fixture response","rationale":"Explicitly reviewed governance changes before reconciliation."}' "$_lc_hashes")" || return; CX_RESUME_OPEN=false; t_good resume; }
scenario_aspects_initialize_once_for_project() { t_ready project || return; CX_RESUME_OPEN=false; t_good resume '{"init_aspects":["local","audited","portable"],"technical_aspects":["shell"],"response_source":"Actual operator fixture response"}' || return; t_bad resume '{"init_aspects":["local","audited","portable"],"response_source":"Actual operator fixture response"}'; }
scenario_completed_execution_cannot_be_relabelled() { t_ready || return; t_field .execution.finished_at '"2026-10-03T00:00:00Z"' || return; t_field .execution.status '"concluida"'; t_good abort || return; t_expect /execution/status concluida; }
scenario_abort_filters_real_secret_from_snapshot_and_report() {
  t_ready || return
  printf 'API_KEY=canary-local-secret-never-publish\n' > "$T_PROJECT/.env"
  t_field .execution.target_project_description '"Local feature canary-local-secret-never-publish"' || return
  t_good abort '{"reason":"Operator aborted the local feature explicitly."}' || return
  if grep -F 'canary-local-secret-never-publish' "$CX_STATE/backups/abort-final.json" "$CX_STATE/feature-00c-report.md" >/dev/null 2>&1; then _fail redaction 'secret leaked in report or backup'; return 1; fi
  [ -f "$CX_STATE/backups/abort-final.json" ]
}
run_all_scenarios
